### ISSUE TITLE
DB: Setup Cassandra cluster 08/16/16

### ISSUE THREAD

**Issue by something15525** [Plantalytics/plantalytics-backend#35]
@stripes416 commented on [Thu Jun 09 2016](https://github.com/Plantalytics/plantalytics-frontend/issues/16)

**!!!!!**_May stick to one node for MVP**_!!!!!**

Set up a two node cluster for our Cassandra DBMS.
~06/10/16-06/11/16~ moved to Final iteration
- [x] Link Bitnami account to Google Cloud Platform
- [ ] Set up two node cluster, with seed nodes (changed from three, per recommendations given to sponsors)
- [x] Deploy Bitnami Cassandra to cluster
- [ ] Verify gossip protocol is fully functional

---

@stripes416 commented on [Wed Jun 15 2016](https://github.com/Plantalytics/plantalytics-frontend/issues/16#issuecomment-226366559)

Half done, but I guess we're resetting the bar a bit. 

---

@SoySauceLabs commented on [Wed Jun 15 2016](https://github.com/Plantalytics/plantalytics-frontend/issues/16#issuecomment-226368069)

oh, lol, lemme move his back into the In Progress lane....

---

@kbrimm commented on [Sat Jul 23 2016](https://github.com/Plantalytics/plantalytics-frontend/issues/16#issuecomment-234738025)

We're still shooting for at least a two-node cluster, right? The-little-node-that-could seems lonely. :(

---

@stripes416 commented on [Sat Jul 23 2016](https://github.com/Plantalytics/plantalytics-frontend/issues/16#issuecomment-234738620)

I don't think so, it wasn't a very high priority during the "priority" meeting

---

@SoySauceLabs commented on [Sat Jul 23 2016](https://github.com/Plantalytics/plantalytics-frontend/issues/16#issuecomment-234738623)

Great question, I will defer to Kelly.... 👼 

---

@SoySauceLabs commented on [Sat Jul 23 2016](https://github.com/Plantalytics/plantalytics-frontend/issues/16#issuecomment-234738846)

That's funny we totally posted at the same moment....

**Comment by SoySauceLabs** [comment]
Well, we gave this one our best shot. But, ultimately, Cassy did not want to play nice. So, she can be stay in time out with the other troublemakers.

Possible future solutions:
- Find someone with Cassandra expertise.
- Pay some $$$ for the "one click cluster setup"....
