### ISSUE TITLE
BE: User info (password/email) change endpoint 08/01/16

### ISSUE THREAD

**Issue by kbrimm** [Plantalytics/plantalytics-backend#41]
- [x] Accepts username, reset token, and new password; verify the reset token is valid, and update the password.
- [x] Accepts a username/auth token + old password + new password to change the password
- [x] Accepts a username/auth token + old password + new email to change the email

**Comment by kbrimm** [comment]
If anyone is looking for something to do this weekend, this task is due in two days and still hasn't been assigned.

**Comment by scotte216** [comment]
This is basically done but is intertwined with issue #40 and is blocked until Matt implements the password function in cassy.py. It's otherwise done.

**Comment by SoySauceLabs** [comment]
Password function implemented -> unblocked! 🔨
