### ISSUE TITLE
DB: Set Up SQLite Database

### ISSUE THREAD

**Issue by SoySauceLabs** [Plantalytics/plantalytics-backend#5]
Implement a SQLite RDBMS to store our "static" data:
- [ ] Set up instance of SQLite database on our Google Cloud Platform host.
- [ ] Create tables (more details in Google Docs repo, Root->Wiki+Reference->DB->Database Design Photots->SQLite Tables & Cassandra Table Updates.jpg):

---
## Tables
- [ ] User
- [ ] Vin_Rel
- [ ] Vineyard
- [ ] Bound_Rel
- [ ] Boundaries
- [ ] Hub_Rel
- [ ] Hub
- [ ] Node_Rel
- [ ] Node

**Comment by kbrimm** [comment]
Will not complete.
